package com.easyeip.jsfboot.admin.bean.impl;

import java.util.ArrayList;
import java.util.List;

import com.easyeip.jsfboot.admin.bean.AdminMenuIconsBean;
import com.easyeip.jsfboot.admin.bean.type.MenuIcon;

public class AdminMenuIconsBeanImpl implements AdminMenuIconsBean {
	
	List<MenuIcon> awesomeIcons;
	List<MenuIcon> rioIcons;
	
	public AdminMenuIconsBeanImpl(){
		awesomeIcons = new ArrayList<MenuIcon>();
		rioIcons = new ArrayList<MenuIcon>();
		initAwesomeIcons();
		initRioIcons();
	}

	@Override
	public List<MenuIcon> getAwesomeIcons() {
		return awesomeIcons;
	}

	@Override
	public List<MenuIcon> getRioIcons() {
		return rioIcons;
	}
	
	private void initRioIcons(){
		rioIcons.add(new MenuIconImpl ("icon-add","icon-add"));
		rioIcons.add(new MenuIconImpl ("icon-alarm","icon-alarm"));
		rioIcons.add(new MenuIconImpl ("icon-anchor","icon-anchor"));
		rioIcons.add(new MenuIconImpl ("icon-attachment","icon-attachment"));
		rioIcons.add(new MenuIconImpl ("icon-brightness","icon-brightness"));
		rioIcons.add(new MenuIconImpl ("icon-brightness-half","icon-brightness-half"));
		rioIcons.add(new MenuIconImpl ("icon-browser","icon-browser"));
		rioIcons.add(new MenuIconImpl ("icon-calculator","icon-calculator"));
		rioIcons.add(new MenuIconImpl ("icon-calendar","icon-calendar"));
		rioIcons.add(new MenuIconImpl ("icon-camera","icon-camera"));
		rioIcons.add(new MenuIconImpl ("icon-chat","icon-chat"));
		rioIcons.add(new MenuIconImpl ("icon-circle-full","icon-circle-full"));
		rioIcons.add(new MenuIconImpl ("icon-circle-half","icon-circle-half"));
		rioIcons.add(new MenuIconImpl ("icon-clipboard","icon-clipboard"));
		rioIcons.add(new MenuIconImpl ("icon-clock","icon-clock"));
		rioIcons.add(new MenuIconImpl ("icon-close","icon-close"));
		rioIcons.add(new MenuIconImpl ("icon-cloud","icon-cloud"));
		rioIcons.add(new MenuIconImpl ("icon-cmd","icon-cmd"));
		rioIcons.add(new MenuIconImpl ("icon-comments","icon-comments"));
		rioIcons.add(new MenuIconImpl ("icon-compose","icon-compose"));
		rioIcons.add(new MenuIconImpl ("icon-delicious","icon-delicious"));
		rioIcons.add(new MenuIconImpl ("icon-dribbble","icon-dribbble"));
		rioIcons.add(new MenuIconImpl ("icon-envelope","icon-envelope"));
		rioIcons.add(new MenuIconImpl ("icon-exclamation","icon-exclamation"));
		rioIcons.add(new MenuIconImpl ("icon-expand","icon-expand"));
		rioIcons.add(new MenuIconImpl ("icon-facebook","icon-facebook"));
		rioIcons.add(new MenuIconImpl ("icon-feather","icon-feather"));
		rioIcons.add(new MenuIconImpl ("icon-forbid","icon-forbid"));
		rioIcons.add(new MenuIconImpl ("icon-forbid-1","icon-forbid-1"));
		rioIcons.add(new MenuIconImpl ("icon-fork-and-knife","icon-fork-and-knife"));
		rioIcons.add(new MenuIconImpl ("icon-fork-and-spoon","icon-fork-and-spoon"));
		rioIcons.add(new MenuIconImpl ("icon-forward","icon-forward"));
		rioIcons.add(new MenuIconImpl ("icon-gallary","icon-gallary"));
		rioIcons.add(new MenuIconImpl ("icon-globe","icon-globe"));
		rioIcons.add(new MenuIconImpl ("icon-googleplus","icon-googleplus"));
		rioIcons.add(new MenuIconImpl ("icon-grid","icon-grid"));
		rioIcons.add(new MenuIconImpl ("icon-grid-alt","icon-grid-alt"));
		rioIcons.add(new MenuIconImpl ("icon-heart","icon-heart"));
		rioIcons.add(new MenuIconImpl ("icon-home","icon-home"));
		rioIcons.add(new MenuIconImpl ("icon-hyperlink","icon-hyperlink"));
		rioIcons.add(new MenuIconImpl ("icon-in","icon-in"));
		rioIcons.add(new MenuIconImpl ("icon-in-alt","icon-in-alt"));
		rioIcons.add(new MenuIconImpl ("icon-inbox","icon-inbox"));
		rioIcons.add(new MenuIconImpl ("icon-inbox-alt","icon-inbox-alt"));
		rioIcons.add(new MenuIconImpl ("icon-instagram","icon-instagram"));
		rioIcons.add(new MenuIconImpl ("icon-ipad","icon-ipad"));
		rioIcons.add(new MenuIconImpl ("icon-iphone","icon-iphone"));
		rioIcons.add(new MenuIconImpl ("icon-light-bulb","icon-light-bulb"));
		rioIcons.add(new MenuIconImpl ("icon-list","icon-list"));
		rioIcons.add(new MenuIconImpl ("icon-maximize","icon-maximize"));
		rioIcons.add(new MenuIconImpl ("icon-menu","icon-menu"));
		rioIcons.add(new MenuIconImpl ("icon-moon","icon-moon"));
		rioIcons.add(new MenuIconImpl ("icon-newspaper","icon-newspaper"));
		rioIcons.add(new MenuIconImpl ("icon-newspaper-alt","icon-newspaper-alt"));
		rioIcons.add(new MenuIconImpl ("icon-out","icon-out"));
		rioIcons.add(new MenuIconImpl ("icon-pause","icon-pause"));
		rioIcons.add(new MenuIconImpl ("icon-pin","icon-pin"));
		rioIcons.add(new MenuIconImpl ("icon-pin-alt","icon-pin-alt"));
		rioIcons.add(new MenuIconImpl ("icon-play","icon-play"));
		rioIcons.add(new MenuIconImpl ("icon-portfolio","icon-portfolio"));
		rioIcons.add(new MenuIconImpl ("icon-question","icon-question"));
		rioIcons.add(new MenuIconImpl ("icon-rewind","icon-rewind"));
		rioIcons.add(new MenuIconImpl ("icon-screen","icon-screen"));
		rioIcons.add(new MenuIconImpl ("icon-search","icon-search"));
		rioIcons.add(new MenuIconImpl ("icon-settings","icon-settings"));
		rioIcons.add(new MenuIconImpl ("icon-sound","icon-sound"));
		rioIcons.add(new MenuIconImpl ("icon-sound-alt","icon-sound-alt"));
		rioIcons.add(new MenuIconImpl ("icon-sound-off","icon-sound-off"));
		rioIcons.add(new MenuIconImpl ("icon-spinner","icon-spinner"));
		rioIcons.add(new MenuIconImpl ("icon-stop","icon-stop"));
		rioIcons.add(new MenuIconImpl ("icon-store","icon-store"));
		rioIcons.add(new MenuIconImpl ("icon-subtract","icon-subtract"));
		rioIcons.add(new MenuIconImpl ("icon-task","icon-task"));
		rioIcons.add(new MenuIconImpl ("icon-trash","icon-trash"));
		rioIcons.add(new MenuIconImpl ("icon-trash-alt","icon-trash-alt"));
		rioIcons.add(new MenuIconImpl ("icon-user","icon-user"));
		rioIcons.add(new MenuIconImpl ("icon-users","icon-users"));
		rioIcons.add(new MenuIconImpl ("icon-windows","icon-windows"));
		rioIcons.add(new MenuIconImpl ("icon-zoom-in","icon-zoom-in"));
		rioIcons.add(new MenuIconImpl ("icon-zoom-out","icon-zoom-out"));
		rioIcons.add(new MenuIconImpl ("icon-celcius","icon-celcius"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-1","icon-cloud-1"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-2","icon-cloud-2"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-black-1","icon-cloud-black-1"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-black-2","icon-cloud-black-2"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-moon","icon-cloud-moon"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-moon-black","icon-cloud-moon-black"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-sun","icon-cloud-sun"));
		rioIcons.add(new MenuIconImpl ("icon-cloud-sun-black","icon-cloud-sun-black"));
		rioIcons.add(new MenuIconImpl ("icon-compass","icon-compass"));
		rioIcons.add(new MenuIconImpl ("icon-farenheit","icon-farenheit"));
		rioIcons.add(new MenuIconImpl ("icon-fog","icon-fog"));
		rioIcons.add(new MenuIconImpl ("icon-fog-cloud","icon-fog-cloud"));
		rioIcons.add(new MenuIconImpl ("icon-fog-moon","icon-fog-moon"));
		rioIcons.add(new MenuIconImpl ("icon-fog-sun","icon-fog-sun"));
		rioIcons.add(new MenuIconImpl ("icon-fog-sunrise","icon-fog-sunrise"));
		rioIcons.add(new MenuIconImpl ("icon-hail","icon-hail"));
		rioIcons.add(new MenuIconImpl ("icon-hail-black","icon-hail-black"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-1","icon-lightning-1"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-2","icon-lightning-2"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-3","icon-lightning-3"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-4","icon-lightning-4"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-black-1","icon-lightning-black-1"));
		rioIcons.add(new MenuIconImpl ("icon-lightning-black-2","icon-lightning-black-2"));
		rioIcons.add(new MenuIconImpl ("icon-moon-1","icon-moon-1"));
		rioIcons.add(new MenuIconImpl ("icon-moon-black","icon-moon-black"));
		rioIcons.add(new MenuIconImpl ("icon-n-a","icon-n-a"));
		rioIcons.add(new MenuIconImpl ("icon-rain-1","icon-rain-1"));
		rioIcons.add(new MenuIconImpl ("icon-rain-2","icon-rain-2"));
		rioIcons.add(new MenuIconImpl ("icon-rain-black-1","icon-rain-black-1"));
		rioIcons.add(new MenuIconImpl ("icon-rain-black-2","icon-rain-black-2"));
		rioIcons.add(new MenuIconImpl ("icon-snow-1","icon-snow-1"));
		rioIcons.add(new MenuIconImpl ("icon-snow-2","icon-snow-2"));
		rioIcons.add(new MenuIconImpl ("icon-snow-3","icon-snow-3"));
		rioIcons.add(new MenuIconImpl ("icon-snow-4","icon-snow-4"));
		rioIcons.add(new MenuIconImpl ("icon-snow-black-1","icon-snow-black-1"));
		rioIcons.add(new MenuIconImpl ("icon-snow-black-2","icon-snow-black-2"));
		rioIcons.add(new MenuIconImpl ("icon-sun","icon-sun"));
		rioIcons.add(new MenuIconImpl ("icon-sun-black","icon-sun-black"));
		rioIcons.add(new MenuIconImpl ("icon-sun-half","icon-sun-half"));
		rioIcons.add(new MenuIconImpl ("icon-sunrise","icon-sunrise"));
		rioIcons.add(new MenuIconImpl ("icon-thermometer","icon-thermometer"));
		rioIcons.add(new MenuIconImpl ("icon-wind","icon-wind"));
		rioIcons.add(new MenuIconImpl ("icon-wind-black","icon-wind-black"));
		rioIcons.add(new MenuIconImpl ("icon-wind-cloud","icon-wind-cloud"));
		rioIcons.add(new MenuIconImpl ("icon-wind-rain","icon-wind-rain"));
		rioIcons.add(new MenuIconImpl ("icon-wind-rain-black","icon-wind-rain-black"));
		rioIcons.add(new MenuIconImpl ("icon-attachment19","icon-attachment19"));
		rioIcons.add(new MenuIconImpl ("icon-auto1","icon-auto1"));
		rioIcons.add(new MenuIconImpl ("icon-automatic2","icon-automatic2"));
		rioIcons.add(new MenuIconImpl ("icon-automatic3","icon-automatic3"));
		rioIcons.add(new MenuIconImpl ("icon-back57","icon-back57"));
		rioIcons.add(new MenuIconImpl ("icon-backspace1","icon-backspace1"));
		rioIcons.add(new MenuIconImpl ("icon-bed24","icon-bed24"));
		rioIcons.add(new MenuIconImpl ("icon-been","icon-been"));
		rioIcons.add(new MenuIconImpl ("icon-birthday20","icon-birthday20"));
		rioIcons.add(new MenuIconImpl ("icon-black394","icon-black394"));
		rioIcons.add(new MenuIconImpl ("icon-black395","icon-black395"));
		rioIcons.add(new MenuIconImpl ("icon-black396","icon-black396"));
		rioIcons.add(new MenuIconImpl ("icon-black397","icon-black397"));
		rioIcons.add(new MenuIconImpl ("icon-black398","icon-black398"));
		rioIcons.add(new MenuIconImpl ("icon-black399","icon-black399"));
		rioIcons.add(new MenuIconImpl ("icon-black400","icon-black400"));
		rioIcons.add(new MenuIconImpl ("icon-black401","icon-black401"));
		rioIcons.add(new MenuIconImpl ("icon-black402","icon-black402"));
		rioIcons.add(new MenuIconImpl ("icon-blank30","icon-blank30"));
		rioIcons.add(new MenuIconImpl ("icon-blank31","icon-blank31"));
		rioIcons.add(new MenuIconImpl ("icon-blank32","icon-blank32"));
		rioIcons.add(new MenuIconImpl ("icon-blank33","icon-blank33"));
		rioIcons.add(new MenuIconImpl ("icon-blogger12","icon-blogger12"));
		rioIcons.add(new MenuIconImpl ("icon-blueetooth","icon-blueetooth"));
		rioIcons.add(new MenuIconImpl ("icon-bluetooth21","icon-bluetooth21"));
		rioIcons.add(new MenuIconImpl ("icon-bluetooth22","icon-bluetooth22"));
		rioIcons.add(new MenuIconImpl ("icon-bluetooth23","icon-bluetooth23"));
		rioIcons.add(new MenuIconImpl ("icon-bluetooth24","icon-bluetooth24"));
		rioIcons.add(new MenuIconImpl ("icon-bluetooth25","icon-bluetooth25"));
		rioIcons.add(new MenuIconImpl ("icon-bookmark45","icon-bookmark45"));
		rioIcons.add(new MenuIconImpl ("icon-bookmark46","icon-bookmark46"));
		rioIcons.add(new MenuIconImpl ("icon-bookmark47","icon-bookmark47"));
		rioIcons.add(new MenuIconImpl ("icon-bookmark48","icon-bookmark48"));
		rioIcons.add(new MenuIconImpl ("icon-briefcase49","icon-briefcase49"));
		rioIcons.add(new MenuIconImpl ("icon-briefcase50","icon-briefcase50"));
		rioIcons.add(new MenuIconImpl ("icon-brightness10","icon-brightness10"));
		rioIcons.add(new MenuIconImpl ("icon-brochure6","icon-brochure6"));
		rioIcons.add(new MenuIconImpl ("icon-bubble8","icon-bubble8"));
		rioIcons.add(new MenuIconImpl ("icon-bug18","icon-bug18"));
		rioIcons.add(new MenuIconImpl ("icon-burn9","icon-burn9"));
		rioIcons.add(new MenuIconImpl ("icon-button11","icon-button11"));
		rioIcons.add(new MenuIconImpl ("icon-call47","icon-call47"));
		rioIcons.add(new MenuIconImpl ("icon-call48","icon-call48"));
		rioIcons.add(new MenuIconImpl ("icon-call49","icon-call49"));
		rioIcons.add(new MenuIconImpl ("icon-camera59","icon-camera59"));
		rioIcons.add(new MenuIconImpl ("icon-camera60","icon-camera60"));
		rioIcons.add(new MenuIconImpl ("icon-cancel19","icon-cancel19"));
		rioIcons.add(new MenuIconImpl ("icon-caps","icon-caps"));
		rioIcons.add(new MenuIconImpl ("icon-caps1","icon-caps1"));
		rioIcons.add(new MenuIconImpl ("icon-car145","icon-car145"));
		rioIcons.add(new MenuIconImpl ("icon-car146","icon-car146"));
		rioIcons.add(new MenuIconImpl ("icon-car147","icon-car147"));
		rioIcons.add(new MenuIconImpl ("icon-cell10","icon-cell10"));
		rioIcons.add(new MenuIconImpl ("icon-cell11","icon-cell11"));
		rioIcons.add(new MenuIconImpl ("icon-cell12","icon-cell12"));
		rioIcons.add(new MenuIconImpl ("icon-change3","icon-change3"));
		rioIcons.add(new MenuIconImpl ("icon-chat75","icon-chat75"));
		rioIcons.add(new MenuIconImpl ("icon-chat76","icon-chat76"));
		rioIcons.add(new MenuIconImpl ("icon-check51","icon-check51"));
		rioIcons.add(new MenuIconImpl ("icon-check52","icon-check52"));
		rioIcons.add(new MenuIconImpl ("icon-chemistry17","icon-chemistry17"));
		rioIcons.add(new MenuIconImpl ("icon-circle107","icon-circle107"));
		rioIcons.add(new MenuIconImpl ("icon-circle108","icon-circle108"));
		rioIcons.add(new MenuIconImpl ("icon-circles23","icon-circles23"));
		rioIcons.add(new MenuIconImpl ("icon-circumference","icon-circumference"));
		rioIcons.add(new MenuIconImpl ("icon-city24","icon-city24"));
		rioIcons.add(new MenuIconImpl ("icon-clapperboard4","icon-clapperboard4"));
		rioIcons.add(new MenuIconImpl ("icon-clapperboard5","icon-clapperboard5"));
		rioIcons.add(new MenuIconImpl ("icon-clear5","icon-clear5"));
		rioIcons.add(new MenuIconImpl ("icon-clipboard99","icon-clipboard99"));
		rioIcons.add(new MenuIconImpl ("icon-clock100","icon-clock100"));
		rioIcons.add(new MenuIconImpl ("icon-close47","icon-close47"));
		rioIcons.add(new MenuIconImpl ("icon-closed64","icon-closed64"));
		rioIcons.add(new MenuIconImpl ("icon-cloud302","icon-cloud302"));
		rioIcons.add(new MenuIconImpl ("icon-cloud303","icon-cloud303"));
		rioIcons.add(new MenuIconImpl ("icon-cloud304","icon-cloud304"));
		rioIcons.add(new MenuIconImpl ("icon-cloud305","icon-cloud305"));
		rioIcons.add(new MenuIconImpl ("icon-cloud306","icon-cloud306"));
		rioIcons.add(new MenuIconImpl ("icon-cloud307","icon-cloud307"));
		rioIcons.add(new MenuIconImpl ("icon-compass106","icon-compass106"));
		rioIcons.add(new MenuIconImpl ("icon-connection21","icon-connection21"));
		rioIcons.add(new MenuIconImpl ("icon-copy31","icon-copy31"));
		rioIcons.add(new MenuIconImpl ("icon-create2","icon-create2"));
		rioIcons.add(new MenuIconImpl ("icon-create3","icon-create3"));
		rioIcons.add(new MenuIconImpl ("icon-credit98","icon-credit98"));
		rioIcons.add(new MenuIconImpl ("icon-crop13","icon-crop13"));
		rioIcons.add(new MenuIconImpl ("icon-crop14","icon-crop14"));
		rioIcons.add(new MenuIconImpl ("icon-cut23","icon-cut23"));
		rioIcons.add(new MenuIconImpl ("icon-dark55","icon-dark55"));
		rioIcons.add(new MenuIconImpl ("icon-developer2","icon-developer2"));
		rioIcons.add(new MenuIconImpl ("icon-device4","icon-device4"));
		rioIcons.add(new MenuIconImpl ("icon-device5","icon-device5"));
		rioIcons.add(new MenuIconImpl ("icon-disc30","icon-disc30"));
		rioIcons.add(new MenuIconImpl ("icon-do10","icon-do10"));
		rioIcons.add(new MenuIconImpl ("icon-double126","icon-double126"));
		rioIcons.add(new MenuIconImpl ("icon-download162","icon-download162"));
		rioIcons.add(new MenuIconImpl ("icon-download164","icon-download164"));
		rioIcons.add(new MenuIconImpl ("icon-download166","icon-download166"));
		rioIcons.add(new MenuIconImpl ("icon-downwards","icon-downwards"));
		rioIcons.add(new MenuIconImpl ("icon-drafts","icon-drafts"));
		rioIcons.add(new MenuIconImpl ("icon-drop25","icon-drop25"));
		rioIcons.add(new MenuIconImpl ("icon-drop26","icon-drop26"));
		rioIcons.add(new MenuIconImpl ("icon-drop27","icon-drop27"));
		rioIcons.add(new MenuIconImpl ("icon-earth205","icon-earth205"));
		rioIcons.add(new MenuIconImpl ("icon-ellipsis1","icon-ellipsis1"));
		rioIcons.add(new MenuIconImpl ("icon-email107","icon-email107"));
		rioIcons.add(new MenuIconImpl ("icon-emoticon117","icon-emoticon117"));
		rioIcons.add(new MenuIconImpl ("icon-end3","icon-end3"));
		rioIcons.add(new MenuIconImpl ("icon-enter5","icon-enter5"));
		rioIcons.add(new MenuIconImpl ("icon-exit13","icon-exit13"));
		rioIcons.add(new MenuIconImpl ("icon-expand38","icon-expand38"));
		rioIcons.add(new MenuIconImpl ("icon-expand39","icon-expand39"));
		rioIcons.add(new MenuIconImpl ("icon-facebook56","icon-facebook56"));
		rioIcons.add(new MenuIconImpl ("icon-fast46","icon-fast46"));
		rioIcons.add(new MenuIconImpl ("icon-favorite21","icon-favorite21"));
		rioIcons.add(new MenuIconImpl ("icon-favorite22","icon-favorite22"));
		rioIcons.add(new MenuIconImpl ("icon-filled13","icon-filled13"));
		rioIcons.add(new MenuIconImpl ("icon-film61","icon-film61"));
		rioIcons.add(new MenuIconImpl ("icon-filter20","icon-filter20"));
		rioIcons.add(new MenuIconImpl ("icon-flash25","icon-flash25"));
		rioIcons.add(new MenuIconImpl ("icon-flash26","icon-flash26"));
		rioIcons.add(new MenuIconImpl ("icon-folder215","icon-folder215"));
		rioIcons.add(new MenuIconImpl ("icon-forward18","icon-forward18"));
		rioIcons.add(new MenuIconImpl ("icon-forward19","icon-forward19"));
		rioIcons.add(new MenuIconImpl ("icon-framed1","icon-framed1"));
		rioIcons.add(new MenuIconImpl ("icon-front15","icon-front15"));
		rioIcons.add(new MenuIconImpl ("icon-front16","icon-front16"));
		rioIcons.add(new MenuIconImpl ("icon-front17","icon-front17"));
		rioIcons.add(new MenuIconImpl ("icon-full46","icon-full46"));
		rioIcons.add(new MenuIconImpl ("icon-gamepad3","icon-gamepad3"));
		rioIcons.add(new MenuIconImpl ("icon-gamepad4","icon-gamepad4"));
		rioIcons.add(new MenuIconImpl ("icon-get","icon-get"));
		rioIcons.add(new MenuIconImpl ("icon-gmail3","icon-gmail3"));
		rioIcons.add(new MenuIconImpl ("icon-go10","icon-go10"));
		rioIcons.add(new MenuIconImpl ("icon-good4","icon-good4"));
		rioIcons.add(new MenuIconImpl ("icon-good5","icon-good5"));
		rioIcons.add(new MenuIconImpl ("icon-google117","icon-google117"));
		rioIcons.add(new MenuIconImpl ("icon-google118","icon-google118"));
		rioIcons.add(new MenuIconImpl ("icon-google119","icon-google119"));
		rioIcons.add(new MenuIconImpl ("icon-google120","icon-google120"));
		rioIcons.add(new MenuIconImpl ("icon-google121","icon-google121"));
		rioIcons.add(new MenuIconImpl ("icon-google122","icon-google122"));
		rioIcons.add(new MenuIconImpl ("icon-google123","icon-google123"));
		rioIcons.add(new MenuIconImpl ("icon-google124","icon-google124"));
		rioIcons.add(new MenuIconImpl ("icon-google125","icon-google125"));
		rioIcons.add(new MenuIconImpl ("icon-google126","icon-google126"));
		rioIcons.add(new MenuIconImpl ("icon-google127","icon-google127"));
		rioIcons.add(new MenuIconImpl ("icon-google128","icon-google128"));
		rioIcons.add(new MenuIconImpl ("icon-google129","icon-google129"));
		rioIcons.add(new MenuIconImpl ("icon-google130","icon-google130"));
		rioIcons.add(new MenuIconImpl ("icon-google131","icon-google131"));
		rioIcons.add(new MenuIconImpl ("icon-google132","icon-google132"));
		rioIcons.add(new MenuIconImpl ("icon-google133","icon-google133"));
		rioIcons.add(new MenuIconImpl ("icon-google134","icon-google134"));
		rioIcons.add(new MenuIconImpl ("icon-google135","icon-google135"));
		rioIcons.add(new MenuIconImpl ("icon-google136","icon-google136"));
		rioIcons.add(new MenuIconImpl ("icon-google137","icon-google137"));
		rioIcons.add(new MenuIconImpl ("icon-gps25","icon-gps25"));
		rioIcons.add(new MenuIconImpl ("icon-gps26","icon-gps26"));
		rioIcons.add(new MenuIconImpl ("icon-gps27","icon-gps27"));
		rioIcons.add(new MenuIconImpl ("icon-gps28","icon-gps28"));
		rioIcons.add(new MenuIconImpl ("icon-graduate32","icon-graduate32"));
		rioIcons.add(new MenuIconImpl ("icon-halffilled1","icon-halffilled1"));
		rioIcons.add(new MenuIconImpl ("icon-hangouts","icon-hangouts"));
		rioIcons.add(new MenuIconImpl ("icon-headset11","icon-headset11"));
		rioIcons.add(new MenuIconImpl ("icon-headset12","icon-headset12"));
		rioIcons.add(new MenuIconImpl ("icon-help18","icon-help18"));
		rioIcons.add(new MenuIconImpl ("icon-help19","icon-help19"));
		rioIcons.add(new MenuIconImpl ("icon-hide3","icon-hide3"));
		rioIcons.add(new MenuIconImpl ("icon-high20","icon-high20"));
		rioIcons.add(new MenuIconImpl ("icon-high21","icon-high21"));
		rioIcons.add(new MenuIconImpl ("icon-high22","icon-high22"));
		rioIcons.add(new MenuIconImpl ("icon-history6","icon-history6"));
		rioIcons.add(new MenuIconImpl ("icon-home149","icon-home149"));
		rioIcons.add(new MenuIconImpl ("icon-horizontal39","icon-horizontal39"));
		rioIcons.add(new MenuIconImpl ("icon-hotel68","icon-hotel68"));
		rioIcons.add(new MenuIconImpl ("icon-https","icon-https"));
		rioIcons.add(new MenuIconImpl ("icon-import","icon-import"));
		rioIcons.add(new MenuIconImpl ("icon-insert4","icon-insert4"));
		rioIcons.add(new MenuIconImpl ("icon-instagram16","icon-instagram16"));
		rioIcons.add(new MenuIconImpl ("icon-invert1","icon-invert1"));
		rioIcons.add(new MenuIconImpl ("icon-keyboard53","icon-keyboard53"));
		rioIcons.add(new MenuIconImpl ("icon-keyboard54","icon-keyboard54"));
		rioIcons.add(new MenuIconImpl ("icon-label31","icon-label31"));
		rioIcons.add(new MenuIconImpl ("icon-landscape10","icon-landscape10"));
		rioIcons.add(new MenuIconImpl ("icon-laptop117","icon-laptop117"));
		rioIcons.add(new MenuIconImpl ("icon-left216","icon-left216"));
		rioIcons.add(new MenuIconImpl ("icon-left217","icon-left217"));
		rioIcons.add(new MenuIconImpl ("icon-left218","icon-left218"));
		rioIcons.add(new MenuIconImpl ("icon-light88","icon-light88"));
		rioIcons.add(new MenuIconImpl ("icon-link60","icon-link60"));
		rioIcons.add(new MenuIconImpl ("icon-linkedin24","icon-linkedin24"));
		rioIcons.add(new MenuIconImpl ("icon-list88","icon-list88"));
		rioIcons.add(new MenuIconImpl ("icon-list89","icon-list89"));
		rioIcons.add(new MenuIconImpl ("icon-location41","icon-location41"));
		rioIcons.add(new MenuIconImpl ("icon-locked57","icon-locked57"));
		rioIcons.add(new MenuIconImpl ("icon-locked58","icon-locked58"));
		rioIcons.add(new MenuIconImpl ("icon-low34","icon-low34"));
		rioIcons.add(new MenuIconImpl ("icon-magic20","icon-magic20"));
		rioIcons.add(new MenuIconImpl ("icon-man459","icon-man459"));
		rioIcons.add(new MenuIconImpl ("icon-man460","icon-man460"));
		rioIcons.add(new MenuIconImpl ("icon-map102","icon-map102"));
		rioIcons.add(new MenuIconImpl ("icon-map103","icon-map103"));
		rioIcons.add(new MenuIconImpl ("icon-mark1","icon-mark1"));
		rioIcons.add(new MenuIconImpl ("icon-mark2","icon-mark2"));
		rioIcons.add(new MenuIconImpl ("icon-medium5","icon-medium5"));
		rioIcons.add(new MenuIconImpl ("icon-medium6","icon-medium6"));
		rioIcons.add(new MenuIconImpl ("icon-medium7","icon-medium7"));
		rioIcons.add(new MenuIconImpl ("icon-memory1","icon-memory1"));
		rioIcons.add(new MenuIconImpl ("icon-menu55","icon-menu55"));
		rioIcons.add(new MenuIconImpl ("icon-merge","icon-merge"));
		rioIcons.add(new MenuIconImpl ("icon-microphone84","icon-microphone84"));
		rioIcons.add(new MenuIconImpl ("icon-microphone85","icon-microphone85"));
		rioIcons.add(new MenuIconImpl ("icon-microsoft7","icon-microsoft7"));
		rioIcons.add(new MenuIconImpl ("icon-microsoft8","icon-microsoft8"));
		rioIcons.add(new MenuIconImpl ("icon-missed","icon-missed"));
		rioIcons.add(new MenuIconImpl ("icon-mountain31","icon-mountain31"));
		rioIcons.add(new MenuIconImpl ("icon-mountain32","icon-mountain32"));
		rioIcons.add(new MenuIconImpl ("icon-mountains14","icon-mountains14"));
		rioIcons.add(new MenuIconImpl ("icon-move26","icon-move26"));
		rioIcons.add(new MenuIconImpl ("icon-new102","icon-new102"));
		rioIcons.add(new MenuIconImpl ("icon-new103","icon-new103"));
		rioIcons.add(new MenuIconImpl ("icon-nfc1","icon-nfc1"));
		rioIcons.add(new MenuIconImpl ("icon-notifications","icon-notifications"));
		rioIcons.add(new MenuIconImpl ("icon-notifications1","icon-notifications1"));
		rioIcons.add(new MenuIconImpl ("icon-notifications2","icon-notifications2"));
		rioIcons.add(new MenuIconImpl ("icon-painter14","icon-painter14"));
		rioIcons.add(new MenuIconImpl ("icon-panoramic1","icon-panoramic1"));
		rioIcons.add(new MenuIconImpl ("icon-parking14","icon-parking14"));
		rioIcons.add(new MenuIconImpl ("icon-pause44","icon-pause44"));
		rioIcons.add(new MenuIconImpl ("icon-person325","icon-person325"));
		rioIcons.add(new MenuIconImpl ("icon-phone370","icon-phone370"));
		rioIcons.add(new MenuIconImpl ("icon-phone371","icon-phone371"));
		rioIcons.add(new MenuIconImpl ("icon-phone372","icon-phone372"));
		rioIcons.add(new MenuIconImpl ("icon-phone373","icon-phone373"));
		rioIcons.add(new MenuIconImpl ("icon-phone374","icon-phone374"));
		rioIcons.add(new MenuIconImpl ("icon-phone375","icon-phone375"));
		rioIcons.add(new MenuIconImpl ("icon-photo210","icon-photo210"));
		rioIcons.add(new MenuIconImpl ("icon-photo211","icon-photo211"));
		rioIcons.add(new MenuIconImpl ("icon-photo212","icon-photo212"));
		rioIcons.add(new MenuIconImpl ("icon-photographic1","icon-photographic1"));
		rioIcons.add(new MenuIconImpl ("icon-pinterest33","icon-pinterest33"));
		rioIcons.add(new MenuIconImpl ("icon-planet29","icon-planet29"));
		rioIcons.add(new MenuIconImpl ("icon-play105","icon-play105"));
		rioIcons.add(new MenuIconImpl ("icon-play106","icon-play106"));
		rioIcons.add(new MenuIconImpl ("icon-play107","icon-play107"));
		rioIcons.add(new MenuIconImpl ("icon-play108","icon-play108"));
		rioIcons.add(new MenuIconImpl ("icon-play109","icon-play109"));
		rioIcons.add(new MenuIconImpl ("icon-plus80","icon-plus80"));
		rioIcons.add(new MenuIconImpl ("icon-poll","icon-poll"));
		rioIcons.add(new MenuIconImpl ("icon-power106","icon-power106"));
		rioIcons.add(new MenuIconImpl ("icon-previous14","icon-previous14"));
		rioIcons.add(new MenuIconImpl ("icon-printer88","icon-printer88"));
		rioIcons.add(new MenuIconImpl ("icon-problems","icon-problems"));
		rioIcons.add(new MenuIconImpl ("icon-progress10","icon-progress10"));
		rioIcons.add(new MenuIconImpl ("icon-public9","icon-public9"));
		rioIcons.add(new MenuIconImpl ("icon-public10","icon-public10"));
		rioIcons.add(new MenuIconImpl ("icon-public11","icon-public11"));
		rioIcons.add(new MenuIconImpl ("icon-puzzle37","icon-puzzle37"));
		rioIcons.add(new MenuIconImpl ("icon-radio51","icon-radio51"));
		rioIcons.add(new MenuIconImpl ("icon-random5","icon-random5"));
		rioIcons.add(new MenuIconImpl ("icon-rate","icon-rate"));
		rioIcons.add(new MenuIconImpl ("icon-read5","icon-read5"));
		rioIcons.add(new MenuIconImpl ("icon-receipt9","icon-receipt9"));
		rioIcons.add(new MenuIconImpl ("icon-record9","icon-record9"));
		rioIcons.add(new MenuIconImpl ("icon-refresh55","icon-refresh55"));
		rioIcons.add(new MenuIconImpl ("icon-refresh56","icon-refresh56"));
		rioIcons.add(new MenuIconImpl ("icon-reminder6","icon-reminder6"));
		rioIcons.add(new MenuIconImpl ("icon-replay4","icon-replay4"));
		rioIcons.add(new MenuIconImpl ("icon-reply18","icon-reply18"));
		rioIcons.add(new MenuIconImpl ("icon-report","icon-report"));
		rioIcons.add(new MenuIconImpl ("icon-rewind45","icon-rewind45"));
		rioIcons.add(new MenuIconImpl ("icon-right237","icon-right237"));
		rioIcons.add(new MenuIconImpl ("icon-right244","icon-right244"));
		rioIcons.add(new MenuIconImpl ("icon-ring24","icon-ring24"));
		rioIcons.add(new MenuIconImpl ("icon-rotate11","icon-rotate11"));
		rioIcons.add(new MenuIconImpl ("icon-rotate12","icon-rotate12"));
		rioIcons.add(new MenuIconImpl ("icon-round50","icon-round50"));
		rioIcons.add(new MenuIconImpl ("icon-round51","icon-round51"));
		rioIcons.add(new MenuIconImpl ("icon-round52","icon-round52"));
		rioIcons.add(new MenuIconImpl ("icon-round53","icon-round53"));
		rioIcons.add(new MenuIconImpl ("icon-round54","icon-round54"));
		rioIcons.add(new MenuIconImpl ("icon-round55","icon-round55"));
		rioIcons.add(new MenuIconImpl ("icon-round56","icon-round56"));
		rioIcons.add(new MenuIconImpl ("icon-round57","icon-round57"));
		rioIcons.add(new MenuIconImpl ("icon-round58","icon-round58"));
		rioIcons.add(new MenuIconImpl ("icon-rounded54","icon-rounded54"));
		rioIcons.add(new MenuIconImpl ("icon-rounded55","icon-rounded55"));
		rioIcons.add(new MenuIconImpl ("icon-rounded56","icon-rounded56"));
		rioIcons.add(new MenuIconImpl ("icon-rounded57","icon-rounded57"));
		rioIcons.add(new MenuIconImpl ("icon-rounded58","icon-rounded58"));
		rioIcons.add(new MenuIconImpl ("icon-rounded59","icon-rounded59"));
		rioIcons.add(new MenuIconImpl ("icon-rounded60","icon-rounded60"));
		rioIcons.add(new MenuIconImpl ("icon-rubbish","icon-rubbish"));
		rioIcons.add(new MenuIconImpl ("icon-save20","icon-save20"));
		rioIcons.add(new MenuIconImpl ("icon-schedule2","icon-schedule2"));
		rioIcons.add(new MenuIconImpl ("icon-screen44","icon-screen44"));
		rioIcons.add(new MenuIconImpl ("icon-screen45","icon-screen45"));
		rioIcons.add(new MenuIconImpl ("icon-screen46","icon-screen46"));
		rioIcons.add(new MenuIconImpl ("icon-screen47","icon-screen47"));
		rioIcons.add(new MenuIconImpl ("icon-screen48","icon-screen48"));
		rioIcons.add(new MenuIconImpl ("icon-screen49","icon-screen49"));
		rioIcons.add(new MenuIconImpl ("icon-sd7","icon-sd7"));
		rioIcons.add(new MenuIconImpl ("icon-sd8","icon-sd8"));
		rioIcons.add(new MenuIconImpl ("icon-search100","icon-search100"));
		rioIcons.add(new MenuIconImpl ("icon-searching41","icon-searching41"));
		rioIcons.add(new MenuIconImpl ("icon-select3","icon-select3"));
		rioIcons.add(new MenuIconImpl ("icon-select4","icon-select4"));
		rioIcons.add(new MenuIconImpl ("icon-send12","icon-send12"));
		rioIcons.add(new MenuIconImpl ("icon-send13","icon-send13"));
		rioIcons.add(new MenuIconImpl ("icon-send14","icon-send14"));
		rioIcons.add(new MenuIconImpl ("icon-server40","icon-server40"));
		rioIcons.add(new MenuIconImpl ("icon-set5","icon-set5"));
		rioIcons.add(new MenuIconImpl ("icon-set6","icon-set6"));
		rioIcons.add(new MenuIconImpl ("icon-settings49","icon-settings49"));
		rioIcons.add(new MenuIconImpl ("icon-settings50","icon-settings50"));
		rioIcons.add(new MenuIconImpl ("icon-share39","icon-share39"));
		rioIcons.add(new MenuIconImpl ("icon-shared1","icon-shared1"));
		rioIcons.add(new MenuIconImpl ("icon-shining2","icon-shining2"));
		rioIcons.add(new MenuIconImpl ("icon-shining3","icon-shining3"));
		rioIcons.add(new MenuIconImpl ("icon-shopping231","icon-shopping231"));
		rioIcons.add(new MenuIconImpl ("icon-shopping232","icon-shopping232"));
		rioIcons.add(new MenuIconImpl ("icon-show4","icon-show4"));
		rioIcons.add(new MenuIconImpl ("icon-show5","icon-show5"));
		rioIcons.add(new MenuIconImpl ("icon-show6","icon-show6"));
		rioIcons.add(new MenuIconImpl ("icon-show7","icon-show7"));
		rioIcons.add(new MenuIconImpl ("icon-show8","icon-show8"));
		rioIcons.add(new MenuIconImpl ("icon-shuffle24","icon-shuffle24"));
		rioIcons.add(new MenuIconImpl ("icon-sim2","icon-sim2"));
		rioIcons.add(new MenuIconImpl ("icon-smartphone19","icon-smartphone19"));
		rioIcons.add(new MenuIconImpl ("icon-smartphone20","icon-smartphone20"));
		rioIcons.add(new MenuIconImpl ("icon-sms5","icon-sms5"));
		rioIcons.add(new MenuIconImpl ("icon-sms6","icon-sms6"));
		rioIcons.add(new MenuIconImpl ("icon-sms7","icon-sms7"));
		rioIcons.add(new MenuIconImpl ("icon-snake4","icon-snake4"));
		rioIcons.add(new MenuIconImpl ("icon-sort52","icon-sort52"));
		rioIcons.add(new MenuIconImpl ("icon-speech108","icon-speech108"));
		rioIcons.add(new MenuIconImpl ("icon-split4","icon-split4"));
		rioIcons.add(new MenuIconImpl ("icon-square181","icon-square181"));
		rioIcons.add(new MenuIconImpl ("icon-stop46","icon-stop46"));
		rioIcons.add(new MenuIconImpl ("icon-swap2","icon-swap2"));
		rioIcons.add(new MenuIconImpl ("icon-swap3","icon-swap3"));
		rioIcons.add(new MenuIconImpl ("icon-switch27","icon-switch27"));
		rioIcons.add(new MenuIconImpl ("icon-switch28","icon-switch28"));
		rioIcons.add(new MenuIconImpl ("icon-switch29","icon-switch29"));
		rioIcons.add(new MenuIconImpl ("icon-switch30","icon-switch30"));
		rioIcons.add(new MenuIconImpl ("icon-synchronization3","icon-synchronization3"));
		rioIcons.add(new MenuIconImpl ("icon-synchronization4","icon-synchronization4"));
		rioIcons.add(new MenuIconImpl ("icon-synchronization5","icon-synchronization5"));
		rioIcons.add(new MenuIconImpl ("icon-tab3","icon-tab3"));
		rioIcons.add(new MenuIconImpl ("icon-tablet95","icon-tablet95"));
		rioIcons.add(new MenuIconImpl ("icon-tack","icon-tack"));
		rioIcons.add(new MenuIconImpl ("icon-tag71","icon-tag71"));
		rioIcons.add(new MenuIconImpl ("icon-telephone105","icon-telephone105"));
		rioIcons.add(new MenuIconImpl ("icon-thermostat1","icon-thermostat1"));
		rioIcons.add(new MenuIconImpl ("icon-three168","icon-three168"));
		rioIcons.add(new MenuIconImpl ("icon-three170","icon-three170"));
		rioIcons.add(new MenuIconImpl ("icon-thumb53","icon-thumb53"));
		rioIcons.add(new MenuIconImpl ("icon-thumb54","icon-thumb54"));
		rioIcons.add(new MenuIconImpl ("icon-tick7","icon-tick7"));
		rioIcons.add(new MenuIconImpl ("icon-timelapse","icon-timelapse"));
		rioIcons.add(new MenuIconImpl ("icon-traffic21","icon-traffic21"));
		rioIcons.add(new MenuIconImpl ("icon-tumblr22","icon-tumblr22"));
		rioIcons.add(new MenuIconImpl ("icon-turn17","icon-turn17"));
		rioIcons.add(new MenuIconImpl ("icon-turn18","icon-turn18"));
		rioIcons.add(new MenuIconImpl ("icon-turn19","icon-turn19"));
		rioIcons.add(new MenuIconImpl ("icon-turn20","icon-turn20"));
		rioIcons.add(new MenuIconImpl ("icon-turn21","icon-turn21"));
		rioIcons.add(new MenuIconImpl ("icon-turn22","icon-turn22"));
		rioIcons.add(new MenuIconImpl ("icon-turn23","icon-turn23"));
		rioIcons.add(new MenuIconImpl ("icon-twitter47","icon-twitter47"));
		rioIcons.add(new MenuIconImpl ("icon-two375","icon-two375"));
		rioIcons.add(new MenuIconImpl ("icon-two385","icon-two385"));
		rioIcons.add(new MenuIconImpl ("icon-two393","icon-two393"));
		rioIcons.add(new MenuIconImpl ("icon-underline6","icon-underline6"));
		rioIcons.add(new MenuIconImpl ("icon-underline7","icon-underline7"));
		rioIcons.add(new MenuIconImpl ("icon-undo19","icon-undo19"));
		rioIcons.add(new MenuIconImpl ("icon-unlocked43","icon-unlocked43"));
		rioIcons.add(new MenuIconImpl ("icon-up176","icon-up176"));
		rioIcons.add(new MenuIconImpl ("icon-upload119","icon-upload119"));
		rioIcons.add(new MenuIconImpl ("icon-upload120","icon-upload120"));
		rioIcons.add(new MenuIconImpl ("icon-usb33","icon-usb33"));
		rioIcons.add(new MenuIconImpl ("icon-user157","icon-user157"));
		rioIcons.add(new MenuIconImpl ("icon-user158","icon-user158"));
		rioIcons.add(new MenuIconImpl ("icon-users25","icon-users25"));
		rioIcons.add(new MenuIconImpl ("icon-verification24","icon-verification24"));
		rioIcons.add(new MenuIconImpl ("icon-videocall","icon-videocall"));
		rioIcons.add(new MenuIconImpl ("icon-view12","icon-view12"));
		rioIcons.add(new MenuIconImpl ("icon-virtual2","icon-virtual2"));
		rioIcons.add(new MenuIconImpl ("icon-visibility1","icon-visibility1"));
		rioIcons.add(new MenuIconImpl ("icon-voice32","icon-voice32"));
		rioIcons.add(new MenuIconImpl ("icon-voicemail1","icon-voicemail1"));
		rioIcons.add(new MenuIconImpl ("icon-volume47","icon-volume47"));
		rioIcons.add(new MenuIconImpl ("icon-volume49","icon-volume49"));
		rioIcons.add(new MenuIconImpl ("icon-volume50","icon-volume50"));
		rioIcons.add(new MenuIconImpl ("icon-volume51","icon-volume51"));
		rioIcons.add(new MenuIconImpl ("icon-warning37","icon-warning37"));
		rioIcons.add(new MenuIconImpl ("icon-watch16","icon-watch16"));
		rioIcons.add(new MenuIconImpl ("icon-waving","icon-waving"));
		rioIcons.add(new MenuIconImpl ("icon-web37","icon-web37"));
		rioIcons.add(new MenuIconImpl ("icon-website12","icon-website12"));
		rioIcons.add(new MenuIconImpl ("icon-wifi81","icon-wifi81"));
		rioIcons.add(new MenuIconImpl ("icon-wifi82","icon-wifi82"));
		rioIcons.add(new MenuIconImpl ("icon-wifi83","icon-wifi83"));
		rioIcons.add(new MenuIconImpl ("icon-window57","icon-window57"));
		rioIcons.add(new MenuIconImpl ("icon-work3","icon-work3"));
		rioIcons.add(new MenuIconImpl ("icon-workspace","icon-workspace"));
		rioIcons.add(new MenuIconImpl ("icon-world96","icon-world96"));
		rioIcons.add(new MenuIconImpl ("icon-write20","icon-write20"));
		rioIcons.add(new MenuIconImpl ("icon-youtube35","icon-youtube35"));
		rioIcons.add(new MenuIconImpl ("icon-account4","icon-account4"));
		rioIcons.add(new MenuIconImpl ("icon-add179","icon-add179"));
		rioIcons.add(new MenuIconImpl ("icon-add180","icon-add180"));
		rioIcons.add(new MenuIconImpl ("icon-add181","icon-add181"));
		rioIcons.add(new MenuIconImpl ("icon-add182","icon-add182"));
		rioIcons.add(new MenuIconImpl ("icon-add183","icon-add183"));
		rioIcons.add(new MenuIconImpl ("icon-add184","icon-add184"));
		rioIcons.add(new MenuIconImpl ("icon-add186","icon-add186"));
		rioIcons.add(new MenuIconImpl ("icon-adjust6","icon-adjust6"));
		rioIcons.add(new MenuIconImpl ("icon-airplane106","icon-airplane106"));
		rioIcons.add(new MenuIconImpl ("icon-android11","icon-android11"));
		rioIcons.add(new MenuIconImpl ("icon-android12","icon-android12"));
		rioIcons.add(new MenuIconImpl ("icon-apple70","icon-apple70"));
	}
	
	private void initAwesomeIcons(){
		awesomeIcons.add(new MenuIconImpl ("fa-bed","fa fa-bed"));
		awesomeIcons.add(new MenuIconImpl ("fa-buysellads","fa fa-buysellads"));
		awesomeIcons.add(new MenuIconImpl ("fa-cart-arrow-down","fa fa-cart-arrow-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-cart-plus","fa fa-cart-plus"));
		awesomeIcons.add(new MenuIconImpl ("fa-connectdevelop","fa fa-connectdevelop"));
		awesomeIcons.add(new MenuIconImpl ("fa-dashcube","fa fa-dashcube"));
		awesomeIcons.add(new MenuIconImpl ("fa-diamond","fa fa-diamond"));
		awesomeIcons.add(new MenuIconImpl ("fa-facebook-official","fa fa-facebook-official"));
		awesomeIcons.add(new MenuIconImpl ("fa-forumbee","fa fa-forumbee"));
		awesomeIcons.add(new MenuIconImpl ("fa-heartbeat","fa fa-heartbeat"));
		awesomeIcons.add(new MenuIconImpl ("fa-hotel","fa fa-hotel"));
		awesomeIcons.add(new MenuIconImpl ("fa-leanpub","fa fa-leanpub"));
		awesomeIcons.add(new MenuIconImpl ("fa-mars","fa fa-mars"));
		awesomeIcons.add(new MenuIconImpl ("fa-mars-double","fa fa-mars-double"));
		awesomeIcons.add(new MenuIconImpl ("fa-mars-stroke","fa fa-mars-stroke"));
		awesomeIcons.add(new MenuIconImpl ("fa-mars-stroke-h","fa fa-mars-stroke-h"));
		awesomeIcons.add(new MenuIconImpl ("fa-mars-stroke-v","fa fa-mars-stroke-v"));
		awesomeIcons.add(new MenuIconImpl ("fa-medium","fa fa-medium"));
		awesomeIcons.add(new MenuIconImpl ("fa-mercury","fa fa-mercury"));
		awesomeIcons.add(new MenuIconImpl ("fa-motorcycle","fa fa-motorcycle"));
		awesomeIcons.add(new MenuIconImpl ("fa-neuter","fa fa-neuter"));
		awesomeIcons.add(new MenuIconImpl ("fa-pinterest-p","fa fa-pinterest-p"));
		awesomeIcons.add(new MenuIconImpl ("fa-sellsy","fa fa-sellsy"));
		awesomeIcons.add(new MenuIconImpl ("fa-server","fa fa-server"));
		awesomeIcons.add(new MenuIconImpl ("fa-ship","fa fa-ship"));
		awesomeIcons.add(new MenuIconImpl ("fa-shirtsinbulk","fa fa-shirtsinbulk"));
		awesomeIcons.add(new MenuIconImpl ("fa-simplybuilt","fa fa-simplybuilt"));
		awesomeIcons.add(new MenuIconImpl ("fa-skyatlas","fa fa-skyatlas"));
		awesomeIcons.add(new MenuIconImpl ("fa-street-view","fa fa-street-view"));
		awesomeIcons.add(new MenuIconImpl ("fa-subway","fa fa-subway"));
		awesomeIcons.add(new MenuIconImpl ("fa-train","fa fa-train"));
		awesomeIcons.add(new MenuIconImpl ("fa-transgender","fa fa-transgender"));
		awesomeIcons.add(new MenuIconImpl ("fa-transgender-alt","fa fa-transgender-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-user-plus","fa fa-user-plus"));
		awesomeIcons.add(new MenuIconImpl ("fa-user-secret","fa fa-user-secret"));
		awesomeIcons.add(new MenuIconImpl ("fa-user-times","fa fa-user-times"));
		awesomeIcons.add(new MenuIconImpl ("fa-venus","fa fa-venus"));
		awesomeIcons.add(new MenuIconImpl ("fa-venus-double","fa fa-venus-double"));
		awesomeIcons.add(new MenuIconImpl ("fa-venus-mars","fa fa-venus-mars"));
		awesomeIcons.add(new MenuIconImpl ("fa-viacoin","fa fa-viacoin"));
		awesomeIcons.add(new MenuIconImpl ("fa-whatsapp","fa fa-whatsapp"));
		awesomeIcons.add(new MenuIconImpl ("fa-adjust","fa fa-adjust"));
		awesomeIcons.add(new MenuIconImpl ("fa-adn","fa fa-adn"));
		awesomeIcons.add(new MenuIconImpl ("fa-align-center","fa fa-align-center"));
		awesomeIcons.add(new MenuIconImpl ("fa-align-justify","fa fa-align-justify"));
		awesomeIcons.add(new MenuIconImpl ("fa-align-left","fa fa-align-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-align-right","fa fa-align-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-ambulance","fa fa-ambulance"));
		awesomeIcons.add(new MenuIconImpl ("fa-anchor","fa fa-anchor"));
		awesomeIcons.add(new MenuIconImpl ("fa-android","fa fa-android"));
		awesomeIcons.add(new MenuIconImpl ("fa-angellist","fa fa-angellist"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-double-down","fa fa-angle-double-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-double-left","fa fa-angle-double-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-double-right","fa fa-angle-double-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-double-up","fa fa-angle-double-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-down","fa fa-angle-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-left","fa fa-angle-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-right","fa fa-angle-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-angle-up","fa fa-angle-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-apple","fa fa-apple"));
		awesomeIcons.add(new MenuIconImpl ("fa-archive","fa fa-archive"));
		awesomeIcons.add(new MenuIconImpl ("fa-area-chart","fa fa-area-chart"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-down","fa fa-arrow-circle-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-left","fa fa-arrow-circle-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-o-down","fa fa-arrow-circle-o-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-o-left","fa fa-arrow-circle-o-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-o-right","fa fa-arrow-circle-o-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-o-up","fa fa-arrow-circle-o-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-right","fa fa-arrow-circle-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-circle-up","fa fa-arrow-circle-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-down","fa fa-arrow-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-left","fa fa-arrow-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-right","fa fa-arrow-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrow-up","fa fa-arrow-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrows","fa fa-arrows"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrows-alt","fa fa-arrows-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrows-h","fa fa-arrows-h"));
		awesomeIcons.add(new MenuIconImpl ("fa-arrows-v","fa fa-arrows-v"));
		awesomeIcons.add(new MenuIconImpl ("fa-asterisk","fa fa-asterisk"));
		awesomeIcons.add(new MenuIconImpl ("fa-at","fa fa-at"));
		awesomeIcons.add(new MenuIconImpl ("fa-automobile","fa fa-automobile"));
		awesomeIcons.add(new MenuIconImpl ("fa-backward","fa fa-backward"));
		awesomeIcons.add(new MenuIconImpl ("fa-ban","fa fa-ban"));
		awesomeIcons.add(new MenuIconImpl ("fa-bank","fa fa-bank"));
		awesomeIcons.add(new MenuIconImpl ("fa-bar-chart","fa fa-bar-chart"));
		awesomeIcons.add(new MenuIconImpl ("fa-bar-chart-o","fa fa-bar-chart-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-barcode","fa fa-barcode"));
		awesomeIcons.add(new MenuIconImpl ("fa-bars","fa fa-bars"));
		awesomeIcons.add(new MenuIconImpl ("fa-beer","fa fa-beer"));
		awesomeIcons.add(new MenuIconImpl ("fa-behance","fa fa-behance"));
		awesomeIcons.add(new MenuIconImpl ("fa-behance-square","fa fa-behance-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-bell","fa fa-bell"));
		awesomeIcons.add(new MenuIconImpl ("fa-bell-o","fa fa-bell-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-bell-slash","fa fa-bell-slash"));
		awesomeIcons.add(new MenuIconImpl ("fa-bell-slash-o","fa fa-bell-slash-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-bicycle","fa fa-bicycle"));
		awesomeIcons.add(new MenuIconImpl ("fa-binoculars","fa fa-binoculars"));
		awesomeIcons.add(new MenuIconImpl ("fa-birthday-cake","fa fa-birthday-cake"));
		awesomeIcons.add(new MenuIconImpl ("fa-bitbucket","fa fa-bitbucket"));
		awesomeIcons.add(new MenuIconImpl ("fa-bitbucket-square","fa fa-bitbucket-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-bitcoin","fa fa-bitcoin"));
		awesomeIcons.add(new MenuIconImpl ("fa-bold","fa fa-bold"));
		awesomeIcons.add(new MenuIconImpl ("fa-bolt","fa fa-bolt"));
		awesomeIcons.add(new MenuIconImpl ("fa-bomb","fa fa-bomb"));
		awesomeIcons.add(new MenuIconImpl ("fa-book","fa fa-book"));
		awesomeIcons.add(new MenuIconImpl ("fa-bookmark","fa fa-bookmark"));
		awesomeIcons.add(new MenuIconImpl ("fa-bookmark-o","fa fa-bookmark-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-briefcase","fa fa-briefcase"));
		awesomeIcons.add(new MenuIconImpl ("fa-btc","fa fa-btc"));
		awesomeIcons.add(new MenuIconImpl ("fa-bug","fa fa-bug"));
		awesomeIcons.add(new MenuIconImpl ("fa-building","fa fa-building"));
		awesomeIcons.add(new MenuIconImpl ("fa-building-o","fa fa-building-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-bullhorn","fa fa-bullhorn"));
		awesomeIcons.add(new MenuIconImpl ("fa-bullseye","fa fa-bullseye"));
		awesomeIcons.add(new MenuIconImpl ("fa-bus","fa fa-bus"));
		awesomeIcons.add(new MenuIconImpl ("fa-cab","fa fa-cab"));
		awesomeIcons.add(new MenuIconImpl ("fa-calculator","fa fa-calculator"));
		awesomeIcons.add(new MenuIconImpl ("fa-calendar","fa fa-calendar"));
		awesomeIcons.add(new MenuIconImpl ("fa-calendar-o","fa fa-calendar-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-camera","fa fa-camera"));
		awesomeIcons.add(new MenuIconImpl ("fa-camera-retro","fa fa-camera-retro"));
		awesomeIcons.add(new MenuIconImpl ("fa-car","fa fa-car"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-down","fa fa-caret-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-left","fa fa-caret-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-right","fa fa-caret-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-square-o-down","fa fa-caret-square-o-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-square-o-left","fa fa-caret-square-o-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-square-o-right","fa fa-caret-square-o-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-square-o-up","fa fa-caret-square-o-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-caret-up","fa fa-caret-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc","fa fa-cc"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-amex","fa fa-cc-amex"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-discover","fa fa-cc-discover"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-mastercard","fa fa-cc-mastercard"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-paypal","fa fa-cc-paypal"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-stripe","fa fa-cc-stripe"));
		awesomeIcons.add(new MenuIconImpl ("fa-cc-visa","fa fa-cc-visa"));
		awesomeIcons.add(new MenuIconImpl ("fa-certificate","fa fa-certificate"));
		awesomeIcons.add(new MenuIconImpl ("fa-chain","fa fa-chain"));
		awesomeIcons.add(new MenuIconImpl ("fa-chain-broken","fa fa-chain-broken"));
		awesomeIcons.add(new MenuIconImpl ("fa-check","fa fa-check"));
		awesomeIcons.add(new MenuIconImpl ("fa-check-circle","fa fa-check-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-check-circle-o","fa fa-check-circle-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-check-square","fa fa-check-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-check-square-o","fa fa-check-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-circle-down","fa fa-chevron-circle-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-circle-left","fa fa-chevron-circle-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-circle-right","fa fa-chevron-circle-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-circle-up","fa fa-chevron-circle-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-down","fa fa-chevron-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-left","fa fa-chevron-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-right","fa fa-chevron-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-chevron-up","fa fa-chevron-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-child","fa fa-child"));
		awesomeIcons.add(new MenuIconImpl ("fa-circle","fa fa-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-circle-o","fa fa-circle-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-circle-o-notch","fa fa-circle-o-notch"));
		awesomeIcons.add(new MenuIconImpl ("fa-circle-thin","fa fa-circle-thin"));
		awesomeIcons.add(new MenuIconImpl ("fa-clipboard","fa fa-clipboard"));
		awesomeIcons.add(new MenuIconImpl ("fa-clock-o","fa fa-clock-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-close","fa fa-close"));
		awesomeIcons.add(new MenuIconImpl ("fa-cloud","fa fa-cloud"));
		awesomeIcons.add(new MenuIconImpl ("fa-cloud-download","fa fa-cloud-download"));
		awesomeIcons.add(new MenuIconImpl ("fa-cloud-upload","fa fa-cloud-upload"));
		awesomeIcons.add(new MenuIconImpl ("fa-cny","fa fa-cny"));
		awesomeIcons.add(new MenuIconImpl ("fa-code","fa fa-code"));
		awesomeIcons.add(new MenuIconImpl ("fa-code-fork","fa fa-code-fork"));
		awesomeIcons.add(new MenuIconImpl ("fa-codepen","fa fa-codepen"));
		awesomeIcons.add(new MenuIconImpl ("fa-coffee","fa fa-coffee"));
		awesomeIcons.add(new MenuIconImpl ("fa-cog","fa fa-cog"));
		awesomeIcons.add(new MenuIconImpl ("fa-cogs","fa fa-cogs"));
		awesomeIcons.add(new MenuIconImpl ("fa-columns","fa fa-columns"));
		awesomeIcons.add(new MenuIconImpl ("fa-comment","fa fa-comment"));
		awesomeIcons.add(new MenuIconImpl ("fa-comment-o","fa fa-comment-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-comments","fa fa-comments"));
		awesomeIcons.add(new MenuIconImpl ("fa-comments-o","fa fa-comments-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-compass","fa fa-compass"));
		awesomeIcons.add(new MenuIconImpl ("fa-compress","fa fa-compress"));
		awesomeIcons.add(new MenuIconImpl ("fa-copy","fa fa-copy"));
		awesomeIcons.add(new MenuIconImpl ("fa-copyright","fa fa-copyright"));
		awesomeIcons.add(new MenuIconImpl ("fa-credit-card","fa fa-credit-card"));
		awesomeIcons.add(new MenuIconImpl ("fa-crop","fa fa-crop"));
		awesomeIcons.add(new MenuIconImpl ("fa-crosshairs","fa fa-crosshairs"));
		awesomeIcons.add(new MenuIconImpl ("fa-css3","fa fa-css3"));
		awesomeIcons.add(new MenuIconImpl ("fa-cube","fa fa-cube"));
		awesomeIcons.add(new MenuIconImpl ("fa-cubes","fa fa-cubes"));
		awesomeIcons.add(new MenuIconImpl ("fa-cut","fa fa-cut"));
		awesomeIcons.add(new MenuIconImpl ("fa-cutlery","fa fa-cutlery"));
		awesomeIcons.add(new MenuIconImpl ("fa-dashboard","fa fa-dashboard"));
		awesomeIcons.add(new MenuIconImpl ("fa-database","fa fa-database"));
		awesomeIcons.add(new MenuIconImpl ("fa-dedent","fa fa-dedent"));
		awesomeIcons.add(new MenuIconImpl ("fa-delicious","fa fa-delicious"));
		awesomeIcons.add(new MenuIconImpl ("fa-desktop","fa fa-desktop"));
		awesomeIcons.add(new MenuIconImpl ("fa-deviantart","fa fa-deviantart"));
		awesomeIcons.add(new MenuIconImpl ("fa-digg","fa fa-digg"));
		awesomeIcons.add(new MenuIconImpl ("fa-dollar","fa fa-dollar"));
		awesomeIcons.add(new MenuIconImpl ("fa-dot-circle-o","fa fa-dot-circle-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-download","fa fa-download"));
		awesomeIcons.add(new MenuIconImpl ("fa-dribbble","fa fa-dribbble"));
		awesomeIcons.add(new MenuIconImpl ("fa-dropbox","fa fa-dropbox"));
		awesomeIcons.add(new MenuIconImpl ("fa-drupal","fa fa-drupal"));
		awesomeIcons.add(new MenuIconImpl ("fa-edit","fa fa-edit"));
		awesomeIcons.add(new MenuIconImpl ("fa-eject","fa fa-eject"));
		awesomeIcons.add(new MenuIconImpl ("fa-ellipsis-h","fa fa-ellipsis-h"));
		awesomeIcons.add(new MenuIconImpl ("fa-ellipsis-v","fa fa-ellipsis-v"));
		awesomeIcons.add(new MenuIconImpl ("fa-empire","fa fa-empire"));
		awesomeIcons.add(new MenuIconImpl ("fa-envelope","fa fa-envelope"));
		awesomeIcons.add(new MenuIconImpl ("fa-envelope-o","fa fa-envelope-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-envelope-square","fa fa-envelope-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-eraser","fa fa-eraser"));
		awesomeIcons.add(new MenuIconImpl ("fa-eur","fa fa-eur"));
		awesomeIcons.add(new MenuIconImpl ("fa-euro","fa fa-euro"));
		awesomeIcons.add(new MenuIconImpl ("fa-exchange","fa fa-exchange"));
		awesomeIcons.add(new MenuIconImpl ("fa-exclamation","fa fa-exclamation"));
		awesomeIcons.add(new MenuIconImpl ("fa-exclamation-circle","fa fa-exclamation-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-exclamation-triangle","fa fa-exclamation-triangle"));
		awesomeIcons.add(new MenuIconImpl ("fa-expand","fa fa-expand"));
		awesomeIcons.add(new MenuIconImpl ("fa-external-link","fa fa-external-link"));
		awesomeIcons.add(new MenuIconImpl ("fa-external-link-square","fa fa-external-link-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-eye","fa fa-eye"));
		awesomeIcons.add(new MenuIconImpl ("fa-eye-slash","fa fa-eye-slash"));
		awesomeIcons.add(new MenuIconImpl ("fa-eyedropper","fa fa-eyedropper"));
		awesomeIcons.add(new MenuIconImpl ("fa-facebook","fa fa-facebook"));
		awesomeIcons.add(new MenuIconImpl ("fa-facebook-square","fa fa-facebook-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-fast-backward","fa fa-fast-backward"));
		awesomeIcons.add(new MenuIconImpl ("fa-fast-forward","fa fa-fast-forward"));
		awesomeIcons.add(new MenuIconImpl ("fa-fax","fa fa-fax"));
		awesomeIcons.add(new MenuIconImpl ("fa-female","fa fa-female"));
		awesomeIcons.add(new MenuIconImpl ("fa-fighter-jet","fa fa-fighter-jet"));
		awesomeIcons.add(new MenuIconImpl ("fa-file","fa fa-file"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-archive-o","fa fa-file-archive-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-audio-o","fa fa-file-audio-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-code-o","fa fa-file-code-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-excel-o","fa fa-file-excel-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-image-o","fa fa-file-image-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-movie-o","fa fa-file-movie-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-o","fa fa-file-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-pdf-o","fa fa-file-pdf-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-photo-o","fa fa-file-photo-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-picture-o","fa fa-file-picture-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-powerpoint-o","fa fa-file-powerpoint-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-sound-o","fa fa-file-sound-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-text","fa fa-file-text"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-text-o","fa fa-file-text-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-video-o","fa fa-file-video-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-word-o","fa fa-file-word-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-file-zip-o","fa fa-file-zip-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-files-o","fa fa-files-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-film","fa fa-film"));
		awesomeIcons.add(new MenuIconImpl ("fa-filter","fa fa-filter"));
		awesomeIcons.add(new MenuIconImpl ("fa-fire","fa fa-fire"));
		awesomeIcons.add(new MenuIconImpl ("fa-fire-extinguisher","fa fa-fire-extinguisher"));
		awesomeIcons.add(new MenuIconImpl ("fa-flag","fa fa-flag"));
		awesomeIcons.add(new MenuIconImpl ("fa-flag-checkered","fa fa-flag-checkered"));
		awesomeIcons.add(new MenuIconImpl ("fa-flag-o","fa fa-flag-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-flash","fa fa-flash"));
		awesomeIcons.add(new MenuIconImpl ("fa-flask","fa fa-flask"));
		awesomeIcons.add(new MenuIconImpl ("fa-flickr","fa fa-flickr"));
		awesomeIcons.add(new MenuIconImpl ("fa-floppy-o","fa fa-floppy-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-folder","fa fa-folder"));
		awesomeIcons.add(new MenuIconImpl ("fa-folder-o","fa fa-folder-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-folder-open","fa fa-folder-open"));
		awesomeIcons.add(new MenuIconImpl ("fa-folder-open-o","fa fa-folder-open-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-font","fa fa-font"));
		awesomeIcons.add(new MenuIconImpl ("fa-forward","fa fa-forward"));
		awesomeIcons.add(new MenuIconImpl ("fa-foursquare","fa fa-foursquare"));
		awesomeIcons.add(new MenuIconImpl ("fa-frown-o","fa fa-frown-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-futbol-o","fa fa-futbol-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-gamepad","fa fa-gamepad"));
		awesomeIcons.add(new MenuIconImpl ("fa-gavel","fa fa-gavel"));
		awesomeIcons.add(new MenuIconImpl ("fa-gbp","fa fa-gbp"));
		awesomeIcons.add(new MenuIconImpl ("fa-ge","fa fa-ge"));
		awesomeIcons.add(new MenuIconImpl ("fa-gear","fa fa-gear"));
		awesomeIcons.add(new MenuIconImpl ("fa-gears","fa fa-gears"));
		awesomeIcons.add(new MenuIconImpl ("fa-gift","fa fa-gift"));
		awesomeIcons.add(new MenuIconImpl ("fa-git","fa fa-git"));
		awesomeIcons.add(new MenuIconImpl ("fa-git-square","fa fa-git-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-github","fa fa-github"));
		awesomeIcons.add(new MenuIconImpl ("fa-github-alt","fa fa-github-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-github-square","fa fa-github-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-gittip","fa fa-gittip"));
		awesomeIcons.add(new MenuIconImpl ("fa-glass","fa fa-glass"));
		awesomeIcons.add(new MenuIconImpl ("fa-globe","fa fa-globe"));
		awesomeIcons.add(new MenuIconImpl ("fa-google","fa fa-google"));
		awesomeIcons.add(new MenuIconImpl ("fa-google-plus","fa fa-google-plus"));
		awesomeIcons.add(new MenuIconImpl ("fa-google-plus-square","fa fa-google-plus-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-google-wallet","fa fa-google-wallet"));
		awesomeIcons.add(new MenuIconImpl ("fa-graduation-cap","fa fa-graduation-cap"));
		awesomeIcons.add(new MenuIconImpl ("fa-group","fa fa-group"));
		awesomeIcons.add(new MenuIconImpl ("fa-h-square","fa fa-h-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-hacker-news","fa fa-hacker-news"));
		awesomeIcons.add(new MenuIconImpl ("fa-hand-o-down","fa fa-hand-o-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-hand-o-left","fa fa-hand-o-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-hand-o-right","fa fa-hand-o-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-hand-o-up","fa fa-hand-o-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-hdd-o","fa fa-hdd-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-header","fa fa-header"));
		awesomeIcons.add(new MenuIconImpl ("fa-headphones","fa fa-headphones"));
		awesomeIcons.add(new MenuIconImpl ("fa-heart","fa fa-heart"));
		awesomeIcons.add(new MenuIconImpl ("fa-heart-o","fa fa-heart-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-history","fa fa-history"));
		awesomeIcons.add(new MenuIconImpl ("fa-home","fa fa-home"));
		awesomeIcons.add(new MenuIconImpl ("fa-hospital-o","fa fa-hospital-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-html5","fa fa-html5"));
		awesomeIcons.add(new MenuIconImpl ("fa-ils","fa fa-ils"));
		awesomeIcons.add(new MenuIconImpl ("fa-image","fa fa-image"));
		awesomeIcons.add(new MenuIconImpl ("fa-inbox","fa fa-inbox"));
		awesomeIcons.add(new MenuIconImpl ("fa-indent","fa fa-indent"));
		awesomeIcons.add(new MenuIconImpl ("fa-info","fa fa-info"));
		awesomeIcons.add(new MenuIconImpl ("fa-info-circle","fa fa-info-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-inr","fa fa-inr"));
		awesomeIcons.add(new MenuIconImpl ("fa-instagram","fa fa-instagram"));
		awesomeIcons.add(new MenuIconImpl ("fa-institution","fa fa-institution"));
		awesomeIcons.add(new MenuIconImpl ("fa-ioxhost","fa fa-ioxhost"));
		awesomeIcons.add(new MenuIconImpl ("fa-italic","fa fa-italic"));
		awesomeIcons.add(new MenuIconImpl ("fa-joomla","fa fa-joomla"));
		awesomeIcons.add(new MenuIconImpl ("fa-jpy","fa fa-jpy"));
		awesomeIcons.add(new MenuIconImpl ("fa-jsfiddle","fa fa-jsfiddle"));
		awesomeIcons.add(new MenuIconImpl ("fa-key","fa fa-key"));
		awesomeIcons.add(new MenuIconImpl ("fa-keyboard-o","fa fa-keyboard-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-krw","fa fa-krw"));
		awesomeIcons.add(new MenuIconImpl ("fa-language","fa fa-language"));
		awesomeIcons.add(new MenuIconImpl ("fa-laptop","fa fa-laptop"));
		awesomeIcons.add(new MenuIconImpl ("fa-lastfm","fa fa-lastfm"));
		awesomeIcons.add(new MenuIconImpl ("fa-lastfm-square","fa fa-lastfm-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-leaf","fa fa-leaf"));
		awesomeIcons.add(new MenuIconImpl ("fa-legal","fa fa-legal"));
		awesomeIcons.add(new MenuIconImpl ("fa-lemon-o","fa fa-lemon-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-level-down","fa fa-level-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-level-up","fa fa-level-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-life-bouy","fa fa-life-bouy"));
		awesomeIcons.add(new MenuIconImpl ("fa-life-buoy","fa fa-life-buoy"));
		awesomeIcons.add(new MenuIconImpl ("fa-life-ring","fa fa-life-ring"));
		awesomeIcons.add(new MenuIconImpl ("fa-life-saver","fa fa-life-saver"));
		awesomeIcons.add(new MenuIconImpl ("fa-lightbulb-o","fa fa-lightbulb-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-line-chart","fa fa-line-chart"));
		awesomeIcons.add(new MenuIconImpl ("fa-link","fa fa-link"));
		awesomeIcons.add(new MenuIconImpl ("fa-linkedin","fa fa-linkedin"));
		awesomeIcons.add(new MenuIconImpl ("fa-linkedin-square","fa fa-linkedin-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-linux","fa fa-linux"));
		awesomeIcons.add(new MenuIconImpl ("fa-list","fa fa-list"));
		awesomeIcons.add(new MenuIconImpl ("fa-list-alt","fa fa-list-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-list-ol","fa fa-list-ol"));
		awesomeIcons.add(new MenuIconImpl ("fa-list-ul","fa fa-list-ul"));
		awesomeIcons.add(new MenuIconImpl ("fa-location-arrow","fa fa-location-arrow"));
		awesomeIcons.add(new MenuIconImpl ("fa-lock","fa fa-lock"));
		awesomeIcons.add(new MenuIconImpl ("fa-long-arrow-down","fa fa-long-arrow-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-long-arrow-left","fa fa-long-arrow-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-long-arrow-right","fa fa-long-arrow-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-long-arrow-up","fa fa-long-arrow-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-magic","fa fa-magic"));
		awesomeIcons.add(new MenuIconImpl ("fa-magnet","fa fa-magnet"));
		awesomeIcons.add(new MenuIconImpl ("fa-mail-forward","fa fa-mail-forward"));
		awesomeIcons.add(new MenuIconImpl ("fa-mail-reply","fa fa-mail-reply"));
		awesomeIcons.add(new MenuIconImpl ("fa-mail-reply-all","fa fa-mail-reply-all"));
		awesomeIcons.add(new MenuIconImpl ("fa-male","fa fa-male"));
		awesomeIcons.add(new MenuIconImpl ("fa-map-marker","fa fa-map-marker"));
		awesomeIcons.add(new MenuIconImpl ("fa-maxcdn","fa fa-maxcdn"));
		awesomeIcons.add(new MenuIconImpl ("fa-meanpath","fa fa-meanpath"));
		awesomeIcons.add(new MenuIconImpl ("fa-medkit","fa fa-medkit"));
		awesomeIcons.add(new MenuIconImpl ("fa-meh-o","fa fa-meh-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-microphone","fa fa-microphone"));
		awesomeIcons.add(new MenuIconImpl ("fa-microphone-slash","fa fa-microphone-slash"));
		awesomeIcons.add(new MenuIconImpl ("fa-minus","fa fa-minus"));
		awesomeIcons.add(new MenuIconImpl ("fa-minus-circle","fa fa-minus-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-minus-square","fa fa-minus-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-minus-square-o","fa fa-minus-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-mobile","fa fa-mobile"));
		awesomeIcons.add(new MenuIconImpl ("fa-mobile-phone","fa fa-mobile-phone"));
		awesomeIcons.add(new MenuIconImpl ("fa-money","fa fa-money"));
		awesomeIcons.add(new MenuIconImpl ("fa-moon-o","fa fa-moon-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-mortar-board","fa fa-mortar-board"));
		awesomeIcons.add(new MenuIconImpl ("fa-music","fa fa-music"));
		awesomeIcons.add(new MenuIconImpl ("fa-navicon","fa fa-navicon"));
		awesomeIcons.add(new MenuIconImpl ("fa-newspaper-o","fa fa-newspaper-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-openid","fa fa-openid"));
		awesomeIcons.add(new MenuIconImpl ("fa-outdent","fa fa-outdent"));
		awesomeIcons.add(new MenuIconImpl ("fa-pagelines","fa fa-pagelines"));
		awesomeIcons.add(new MenuIconImpl ("fa-paint-brush","fa fa-paint-brush"));
		awesomeIcons.add(new MenuIconImpl ("fa-paper-plane","fa fa-paper-plane"));
		awesomeIcons.add(new MenuIconImpl ("fa-paper-plane-o","fa fa-paper-plane-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-paperclip","fa fa-paperclip"));
		awesomeIcons.add(new MenuIconImpl ("fa-paragraph","fa fa-paragraph"));
		awesomeIcons.add(new MenuIconImpl ("fa-paste","fa fa-paste"));
		awesomeIcons.add(new MenuIconImpl ("fa-pause","fa fa-pause"));
		awesomeIcons.add(new MenuIconImpl ("fa-paw","fa fa-paw"));
		awesomeIcons.add(new MenuIconImpl ("fa-paypal","fa fa-paypal"));
		awesomeIcons.add(new MenuIconImpl ("fa-pencil","fa fa-pencil"));
		awesomeIcons.add(new MenuIconImpl ("fa-pencil-square","fa fa-pencil-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-pencil-square-o","fa fa-pencil-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-phone","fa fa-phone"));
		awesomeIcons.add(new MenuIconImpl ("fa-phone-square","fa fa-phone-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-photo","fa fa-photo"));
		awesomeIcons.add(new MenuIconImpl ("fa-picture-o","fa fa-picture-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-pie-chart","fa fa-pie-chart"));
		awesomeIcons.add(new MenuIconImpl ("fa-pied-piper","fa fa-pied-piper"));
		awesomeIcons.add(new MenuIconImpl ("fa-pied-piper-alt","fa fa-pied-piper-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-pinterest","fa fa-pinterest"));
		awesomeIcons.add(new MenuIconImpl ("fa-pinterest-square","fa fa-pinterest-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-plane","fa fa-plane"));
		awesomeIcons.add(new MenuIconImpl ("fa-play","fa fa-play"));
		awesomeIcons.add(new MenuIconImpl ("fa-play-circle","fa fa-play-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-play-circle-o","fa fa-play-circle-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-plug","fa fa-plug"));
		awesomeIcons.add(new MenuIconImpl ("fa-plus","fa fa-plus"));
		awesomeIcons.add(new MenuIconImpl ("fa-plus-circle","fa fa-plus-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-plus-square","fa fa-plus-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-plus-square-o","fa fa-plus-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-power-off","fa fa-power-off"));
		awesomeIcons.add(new MenuIconImpl ("fa-print","fa fa-print"));
		awesomeIcons.add(new MenuIconImpl ("fa-puzzle-piece","fa fa-puzzle-piece"));
		awesomeIcons.add(new MenuIconImpl ("fa-qq","fa fa-qq"));
		awesomeIcons.add(new MenuIconImpl ("fa-qrcode","fa fa-qrcode"));
		awesomeIcons.add(new MenuIconImpl ("fa-question","fa fa-question"));
		awesomeIcons.add(new MenuIconImpl ("fa-question-circle","fa fa-question-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-quote-left","fa fa-quote-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-quote-right","fa fa-quote-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-ra","fa fa-ra"));
		awesomeIcons.add(new MenuIconImpl ("fa-random","fa fa-random"));
		awesomeIcons.add(new MenuIconImpl ("fa-rebel","fa fa-rebel"));
		awesomeIcons.add(new MenuIconImpl ("fa-recycle","fa fa-recycle"));
		awesomeIcons.add(new MenuIconImpl ("fa-reddit","fa fa-reddit"));
		awesomeIcons.add(new MenuIconImpl ("fa-reddit-square","fa fa-reddit-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-refresh","fa fa-refresh"));
		awesomeIcons.add(new MenuIconImpl ("fa-remove","fa fa-remove"));
		awesomeIcons.add(new MenuIconImpl ("fa-renren","fa fa-renren"));
		awesomeIcons.add(new MenuIconImpl ("fa-reorder","fa fa-reorder"));
		awesomeIcons.add(new MenuIconImpl ("fa-repeat","fa fa-repeat"));
		awesomeIcons.add(new MenuIconImpl ("fa-reply","fa fa-reply"));
		awesomeIcons.add(new MenuIconImpl ("fa-reply-all","fa fa-reply-all"));
		awesomeIcons.add(new MenuIconImpl ("fa-retweet","fa fa-retweet"));
		awesomeIcons.add(new MenuIconImpl ("fa-rmb","fa fa-rmb"));
		awesomeIcons.add(new MenuIconImpl ("fa-road","fa fa-road"));
		awesomeIcons.add(new MenuIconImpl ("fa-rocket","fa fa-rocket"));
		awesomeIcons.add(new MenuIconImpl ("fa-rotate-left","fa fa-rotate-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-rotate-right","fa fa-rotate-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-rouble","fa fa-rouble"));
		awesomeIcons.add(new MenuIconImpl ("fa-rss","fa fa-rss"));
		awesomeIcons.add(new MenuIconImpl ("fa-rss-square","fa fa-rss-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-rub","fa fa-rub"));
		awesomeIcons.add(new MenuIconImpl ("fa-ruble","fa fa-ruble"));
		awesomeIcons.add(new MenuIconImpl ("fa-rupee","fa fa-rupee"));
		awesomeIcons.add(new MenuIconImpl ("fa-save","fa fa-save"));
		awesomeIcons.add(new MenuIconImpl ("fa-scissors","fa fa-scissors"));
		awesomeIcons.add(new MenuIconImpl ("fa-search","fa fa-search"));
		awesomeIcons.add(new MenuIconImpl ("fa-search-minus","fa fa-search-minus"));
		awesomeIcons.add(new MenuIconImpl ("fa-search-plus","fa fa-search-plus"));
		awesomeIcons.add(new MenuIconImpl ("fa-send","fa fa-send"));
		awesomeIcons.add(new MenuIconImpl ("fa-send-o","fa fa-send-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-share","fa fa-share"));
		awesomeIcons.add(new MenuIconImpl ("fa-share-alt","fa fa-share-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-share-alt-square","fa fa-share-alt-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-share-square","fa fa-share-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-share-square-o","fa fa-share-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-shekel","fa fa-shekel"));
		awesomeIcons.add(new MenuIconImpl ("fa-sheqel","fa fa-sheqel"));
		awesomeIcons.add(new MenuIconImpl ("fa-shield","fa fa-shield"));
		awesomeIcons.add(new MenuIconImpl ("fa-shopping-cart","fa fa-shopping-cart"));
		awesomeIcons.add(new MenuIconImpl ("fa-sign-in","fa fa-sign-in"));
		awesomeIcons.add(new MenuIconImpl ("fa-sign-out","fa fa-sign-out"));
		awesomeIcons.add(new MenuIconImpl ("fa-signal","fa fa-signal"));
		awesomeIcons.add(new MenuIconImpl ("fa-sitemap","fa fa-sitemap"));
		awesomeIcons.add(new MenuIconImpl ("fa-skype","fa fa-skype"));
		awesomeIcons.add(new MenuIconImpl ("fa-slack","fa fa-slack"));
		awesomeIcons.add(new MenuIconImpl ("fa-sliders","fa fa-sliders"));
		awesomeIcons.add(new MenuIconImpl ("fa-slideshare","fa fa-slideshare"));
		awesomeIcons.add(new MenuIconImpl ("fa-smile-o","fa fa-smile-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-soccer-ball-o","fa fa-soccer-ball-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort","fa fa-sort"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-alpha-asc","fa fa-sort-alpha-asc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-alpha-desc","fa fa-sort-alpha-desc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-amount-asc","fa fa-sort-amount-asc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-amount-desc","fa fa-sort-amount-desc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-asc","fa fa-sort-asc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-desc","fa fa-sort-desc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-down","fa fa-sort-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-numeric-asc","fa fa-sort-numeric-asc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-numeric-desc","fa fa-sort-numeric-desc"));
		awesomeIcons.add(new MenuIconImpl ("fa-sort-up","fa fa-sort-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-soundcloud","fa fa-soundcloud"));
		awesomeIcons.add(new MenuIconImpl ("fa-space-shuttle","fa fa-space-shuttle"));
		awesomeIcons.add(new MenuIconImpl ("fa-spinner","fa fa-spinner"));
		awesomeIcons.add(new MenuIconImpl ("fa-spoon","fa fa-spoon"));
		awesomeIcons.add(new MenuIconImpl ("fa-spotify","fa fa-spotify"));
		awesomeIcons.add(new MenuIconImpl ("fa-square","fa fa-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-square-o","fa fa-square-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-stack-exchange","fa fa-stack-exchange"));
		awesomeIcons.add(new MenuIconImpl ("fa-stack-overflow","fa fa-stack-overflow"));
		awesomeIcons.add(new MenuIconImpl ("fa-star","fa fa-star"));
		awesomeIcons.add(new MenuIconImpl ("fa-star-half","fa fa-star-half"));
		awesomeIcons.add(new MenuIconImpl ("fa-star-half-empty","fa fa-star-half-empty"));
		awesomeIcons.add(new MenuIconImpl ("fa-star-half-full","fa fa-star-half-full"));
		awesomeIcons.add(new MenuIconImpl ("fa-star-half-o","fa fa-star-half-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-star-o","fa fa-star-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-steam","fa fa-steam"));
		awesomeIcons.add(new MenuIconImpl ("fa-steam-square","fa fa-steam-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-step-backward","fa fa-step-backward"));
		awesomeIcons.add(new MenuIconImpl ("fa-step-forward","fa fa-step-forward"));
		awesomeIcons.add(new MenuIconImpl ("fa-stethoscope","fa fa-stethoscope"));
		awesomeIcons.add(new MenuIconImpl ("fa-stop","fa fa-stop"));
		awesomeIcons.add(new MenuIconImpl ("fa-strikethrough","fa fa-strikethrough"));
		awesomeIcons.add(new MenuIconImpl ("fa-stumbleupon","fa fa-stumbleupon"));
		awesomeIcons.add(new MenuIconImpl ("fa-stumbleupon-circle","fa fa-stumbleupon-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-subscript","fa fa-subscript"));
		awesomeIcons.add(new MenuIconImpl ("fa-suitcase","fa fa-suitcase"));
		awesomeIcons.add(new MenuIconImpl ("fa-sun-o","fa fa-sun-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-superscript","fa fa-superscript"));
		awesomeIcons.add(new MenuIconImpl ("fa-support","fa fa-support"));
		awesomeIcons.add(new MenuIconImpl ("fa-table","fa fa-table"));
		awesomeIcons.add(new MenuIconImpl ("fa-tablet","fa fa-tablet"));
		awesomeIcons.add(new MenuIconImpl ("fa-tachometer","fa fa-tachometer"));
		awesomeIcons.add(new MenuIconImpl ("fa-tag","fa fa-tag"));
		awesomeIcons.add(new MenuIconImpl ("fa-tags","fa fa-tags"));
		awesomeIcons.add(new MenuIconImpl ("fa-tasks","fa fa-tasks"));
		awesomeIcons.add(new MenuIconImpl ("fa-taxi","fa fa-taxi"));
		awesomeIcons.add(new MenuIconImpl ("fa-tencent-weibo","fa fa-tencent-weibo"));
		awesomeIcons.add(new MenuIconImpl ("fa-terminal","fa fa-terminal"));
		awesomeIcons.add(new MenuIconImpl ("fa-text-height","fa fa-text-height"));
		awesomeIcons.add(new MenuIconImpl ("fa-text-width","fa fa-text-width"));
		awesomeIcons.add(new MenuIconImpl ("fa-th","fa fa-th"));
		awesomeIcons.add(new MenuIconImpl ("fa-th-large","fa fa-th-large"));
		awesomeIcons.add(new MenuIconImpl ("fa-th-list","fa fa-th-list"));
		awesomeIcons.add(new MenuIconImpl ("fa-thumb-tack","fa fa-thumb-tack"));
		awesomeIcons.add(new MenuIconImpl ("fa-thumbs-down","fa fa-thumbs-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-thumbs-o-down","fa fa-thumbs-o-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-thumbs-o-up","fa fa-thumbs-o-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-thumbs-up","fa fa-thumbs-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-ticket","fa fa-ticket"));
		awesomeIcons.add(new MenuIconImpl ("fa-times","fa fa-times"));
		awesomeIcons.add(new MenuIconImpl ("fa-times-circle","fa fa-times-circle"));
		awesomeIcons.add(new MenuIconImpl ("fa-times-circle-o","fa fa-times-circle-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-tint","fa fa-tint"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-down","fa fa-toggle-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-left","fa fa-toggle-left"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-off","fa fa-toggle-off"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-on","fa fa-toggle-on"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-right","fa fa-toggle-right"));
		awesomeIcons.add(new MenuIconImpl ("fa-toggle-up","fa fa-toggle-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-trash","fa fa-trash"));
		awesomeIcons.add(new MenuIconImpl ("fa-trash-o","fa fa-trash-o"));
		awesomeIcons.add(new MenuIconImpl ("fa-tree","fa fa-tree"));
		awesomeIcons.add(new MenuIconImpl ("fa-trello","fa fa-trello"));
		awesomeIcons.add(new MenuIconImpl ("fa-trophy","fa fa-trophy"));
		awesomeIcons.add(new MenuIconImpl ("fa-truck","fa fa-truck"));
		awesomeIcons.add(new MenuIconImpl ("fa-try","fa fa-try"));
		awesomeIcons.add(new MenuIconImpl ("fa-tty","fa fa-tty"));
		awesomeIcons.add(new MenuIconImpl ("fa-tumblr","fa fa-tumblr"));
		awesomeIcons.add(new MenuIconImpl ("fa-tumblr-square","fa fa-tumblr-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-turkish-lira","fa fa-turkish-lira"));
		awesomeIcons.add(new MenuIconImpl ("fa-twitch","fa fa-twitch"));
		awesomeIcons.add(new MenuIconImpl ("fa-twitter","fa fa-twitter"));
		awesomeIcons.add(new MenuIconImpl ("fa-twitter-square","fa fa-twitter-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-umbrella","fa fa-umbrella"));
		awesomeIcons.add(new MenuIconImpl ("fa-underline","fa fa-underline"));
		awesomeIcons.add(new MenuIconImpl ("fa-undo","fa fa-undo"));
		awesomeIcons.add(new MenuIconImpl ("fa-university","fa fa-university"));
		awesomeIcons.add(new MenuIconImpl ("fa-unlink","fa fa-unlink"));
		awesomeIcons.add(new MenuIconImpl ("fa-unlock","fa fa-unlock"));
		awesomeIcons.add(new MenuIconImpl ("fa-unlock-alt","fa fa-unlock-alt"));
		awesomeIcons.add(new MenuIconImpl ("fa-unsorted","fa fa-unsorted"));
		awesomeIcons.add(new MenuIconImpl ("fa-upload","fa fa-upload"));
		awesomeIcons.add(new MenuIconImpl ("fa-usd","fa fa-usd"));
		awesomeIcons.add(new MenuIconImpl ("fa-user","fa fa-user"));
		awesomeIcons.add(new MenuIconImpl ("fa-user-md","fa fa-user-md"));
		awesomeIcons.add(new MenuIconImpl ("fa-users","fa fa-users"));
		awesomeIcons.add(new MenuIconImpl ("fa-video-camera","fa fa-video-camera"));
		awesomeIcons.add(new MenuIconImpl ("fa-vimeo-square","fa fa-vimeo-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-vine","fa fa-vine"));
		awesomeIcons.add(new MenuIconImpl ("fa-vk","fa fa-vk"));
		awesomeIcons.add(new MenuIconImpl ("fa-volume-down","fa fa-volume-down"));
		awesomeIcons.add(new MenuIconImpl ("fa-volume-off","fa fa-volume-off"));
		awesomeIcons.add(new MenuIconImpl ("fa-volume-up","fa fa-volume-up"));
		awesomeIcons.add(new MenuIconImpl ("fa-warning","fa fa-warning"));
		awesomeIcons.add(new MenuIconImpl ("fa-wechat","fa fa-wechat"));
		awesomeIcons.add(new MenuIconImpl ("fa-weibo","fa fa-weibo"));
		awesomeIcons.add(new MenuIconImpl ("fa-weixin","fa fa-weixin"));
		awesomeIcons.add(new MenuIconImpl ("fa-wheelchair","fa fa-wheelchair"));
		awesomeIcons.add(new MenuIconImpl ("fa-wifi","fa fa-wifi"));
		awesomeIcons.add(new MenuIconImpl ("fa-windows","fa fa-windows"));
		awesomeIcons.add(new MenuIconImpl ("fa-won","fa fa-won"));
		awesomeIcons.add(new MenuIconImpl ("fa-wordpress","fa fa-wordpress"));
		awesomeIcons.add(new MenuIconImpl ("fa-wrench","fa fa-wrench"));
		awesomeIcons.add(new MenuIconImpl ("fa-xing","fa fa-xing"));
		awesomeIcons.add(new MenuIconImpl ("fa-xing-square","fa fa-xing-square"));
		awesomeIcons.add(new MenuIconImpl ("fa-yahoo","fa fa-yahoo"));
		awesomeIcons.add(new MenuIconImpl ("fa-yelp","fa fa-yelp"));
		awesomeIcons.add(new MenuIconImpl ("fa-yen","fa fa-yen"));
		awesomeIcons.add(new MenuIconImpl ("fa-youtube","fa fa-youtube"));
		awesomeIcons.add(new MenuIconImpl ("fa-youtube-play","fa fa-youtube-play"));
		awesomeIcons.add(new MenuIconImpl ("fa-youtube-square","fa fa-youtube-square"));
	}
}
